FROM public.ecr.aws/lambda/python:3.12

# Copiar el código de la función
COPY lambda_postgres_writer.py ${LAMBDA_TASK_ROOT}/

# Instalar dependencias
RUN pip install --no-cache-dir psycopg2-binary boto3

# Set the CMD to your handler
CMD [ "lambda_postgres_writer.lambda_handler" ]
